In [147]:
%matplotlib notebook
from scipy import sparse 
from scipy.sparse.linalg import lsqr, cg, eigsh
import matplotlib.pyplot as plt 
import argparse
from mpl_toolkits.axes_grid1 import make_axes_locatable
from mpl_toolkits.mplot3d import Axes3D
import cv2
import heapq
import random
import copy
import sys
from sklearn.cluster import KMeans
from sklearn.linear_model import LinearRegression
from sklearn.decomposition import PCA
import pandas as pd
from scipy.spatial import ConvexHull
from mpl_toolkits.mplot3d import Axes3D
from scipy import genfromtxt
from sklearn.cluster import SpectralClustering
import matplotlib.patches as mpatches
import importlib
import time

import hks
import saiteki as h

In [148]:
importlib.reload(hks)
importlib.reload(h)
from hks import *

In [149]:
#骨格の長さを計算する関数
def bonelen(trc):
    joint = trc[:,1:]
    #配列作り
    a = np.arange(17)
    a[4] = 1
    a[7] = 1
    a[10] = 1
    a[13] = 0
    a[14] = 0
    a[-2:] -=1
    c = np.zeros(17*3,dtype='int32')
    c[::3] = a*3
    c[1::3] =a*3+1
    c[2::3] =a*3+2
    jointbox = (joint[:,1*3:]-joint[:,c])**2
    jointbox = np.reshape(jointbox,(len(jointbox),17,3))
    jointlen = np.sum(jointbox,axis=2)**0.5
    return jointlen

In [7]:
#trcから骨格長の計算
#a = pd.read_csv('trc/model1.trc',delim_whitespace=True)
lst = [1,2,3,4]
for i in lst:
    a = pd.read_table('trc/model{}.trc'.format(i),header=4)
    b = a.values
    trc = b[:,:-1]
    length = bonelen(trc)
#保存
#    np.savetxt("trc/bonelength{}.csv".format(i),length,delimiter=',')

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """


In [150]:
#読み込み
bl1 = np.loadtxt("trc/bonelength1.csv",delimiter=',')
bl2 = np.loadtxt("trc/bonelength2.csv",delimiter=',')
bl3 = np.loadtxt("trc/bonelength3.csv",delimiter=',')
bl4 = np.loadtxt("trc/bonelength4.csv",delimiter=',')
lst = [1,2,3,4]
print(np.shape(bl1))

(4663, 17)


In [151]:
#結果の割合
#結果の割合

#ベースモデルを作る
base1 = np.mean(bl1[500:1100],axis=0)
base2 = np.mean(bl2[1200:1800],axis=0)
base3 = np.mean(bl3[600:1200],axis=0)
base4 = np.mean(bl4[600:1200],axis=0)
#テストモデルを作る
test1 = np.mean(np.reshape(bl1[3300:4500],(20,60,17)),axis=1)
test2 = np.mean(np.reshape(bl2[1800:3000],(20,60,17)),axis=1)
test3 = np.mean(np.reshape(bl3[1300:2500],(20,60,17)),axis=1)
test4 = np.mean(np.reshape(bl4[1300:2500],(20,60,17)),axis=1)
for name in lst:
    exec("ansbox%d =np.zeros((20,4))"%(name))
    for i,j in enumerate(lst):
#普通の結果
        exec("ansbox%d[:,i] = np.sum(np.abs(test%d-base%d),axis=1)"%(name,name,j))
    exec("indbox%d = np.argsort(ansbox%d,axis=1)+1"%(name,name))
#print(ansbox1)
#print(ansbox2)
#print(ansbox3)
#print(ansbox4)
#print(np.sum(indbox1[:,0] ==1)/20)
#print(np.sum(indbox2[:,0] ==2)/20)
#print(np.sum(indbox3[:,0] ==3)/20)
#print(np.sum(indbox4[:,0] ==4)/20)
#print(indbox1)
#print(indbox2)
#print(indbox3)
#print(indbox4)


ここからすきんモデルを用いたやつをおこなう

In [152]:
importlib.reload(hks)
importlib.reload(h)
from hks import *
#(a,b,c) = h.hkscolor('doudemoii/000_40.obj','doudemoii/aaa40',1000)
#(a,b,c) = h.hkscolor('poseobj/model2frame1201.obj','result/',700)
#(a,b,c) = h.hkscolor('objdata/model1.obj','result/5baiaa',700)


In [186]:
##ベースデータ
##まとめて保存
#h.matome_hc(500 ,60,1)
#h.matome_hc(1200,60,2)
#h.matome_hc(600 ,60,3)
#h.matome_hc(600 ,60,4)

In [207]:
##ベースデータ
##まとめて保存
#sframe = 500
#ran = 60
#for i in range(ran):
#    frame = sframe +i*10+1
#    np.savetxt("hks/areamodel{:d}frame{:04d}.csv".format(1,frame),h.solve_hc(1,frame)[:,0],delimiter=',')
#sframe = 1200
#for i in range(ran):
#    frame = sframe +i*10+1
#    np.savetxt("hks/areamodel{:d}frame{:04d}.csv".format(2,frame),h.solve_hc(2,frame)[:,0],delimiter=',')
#sframe = 600
#for i in range(ran):
#    frame = sframe +i*10+1
#    np.savetxt("hks/areamodel{:d}frame{:04d}.csv".format(3,frame),h.solve_hc(3,frame)[:,0],delimiter=',')
#for i in range(ran):
#    frame = sframe +i*10+1
#    np.savetxt("hks/areamodel{:d}frame{:04d}.csv".format(4,frame),h.solve_hc(4,frame)[:,0],delimiter=',')

In [10]:
###テストデータ
###まとめて保存
#h.matome_hc(3300 ,20,1)
#h.matome_hc(1800 ,20,2)
#h.matome_hc(1300 ,20,3)
#h.matome_hc(1300 ,20,4)
#sframe =3300 
#ran = 20
#for i in range(ran):
#    frame = sframe +i*10+1
#    np.savetxt("hks/areamodel{:d}frame{:04d}.csv".format(1,frame),h.solve_hc(1,frame)[:,0],delimiter=',')
#sframe = 1800
#for i in range(ran):
#    frame = sframe +i*10+1
#    np.savetxt("hks/areamodel{:d}frame{:04d}.csv".format(2,frame),h.solve_hc(2,frame)[:,0],delimiter=',')
#sframe = 1300
#for i in range(ran):
#    frame = sframe +i*10+1
#    np.savetxt("hks/areamodel{:d}frame{:04d}.csv".format(3,frame),h.solve_hc(3,frame)[:,0],delimiter=',')
#for i in range(ran):
#    frame = sframe +i*10+1
#    np.savetxt("hks/areamodel{:d}frame{:04d}.csv".format(4,frame),h.solve_hc(4,frame)[:,0],delimiter=',')

In [153]:
def alsort(array):
    alsort = np.zeros(11)
    alsort[:2] = np.sort(array[:2])
    alsort[2:6] = np.sort(array[2:6])
    alsort[6] = np.max(array[6:9])
    alsort[7:] = np.sort(array[9:])
    return alsort

In [154]:
ran = 60
sframe1 = 500
sframe2 =1200
sframe3 = 600
sframe4 = 600
al1b = np.zeros((ran,11))
al2b = np.zeros((ran,11))
al3b = np.zeros((ran,11))
al4b = np.zeros((ran,11))
for i in range(ran):
    frame1 = sframe1 +i*10+1
    frame2 = sframe2 +i*10+1
    frame3 = sframe3 +i*10+1
    frame4 = sframe4 +i*10+1
    al1b[i] = alsort(np.loadtxt('hks/areamodel{:d}frame{:04d}.csv'.format(1,frame1),delimiter=','))
    al2b[i] = alsort(np.loadtxt('hks/areamodel{:d}frame{:04d}.csv'.format(2,frame2),delimiter=','))
    al3b[i] = alsort(np.loadtxt('hks/areamodel{:d}frame{:04d}.csv'.format(3,frame3),delimiter=','))
    al4b[i] = alsort(np.loadtxt('hks/areamodel{:d}frame{:04d}.csv'.format(4,frame4),delimiter=','))
ab1 = np.mean(al1b,axis=0)
ab2 = np.mean(al2b,axis=0)
ab3 = np.mean(al3b,axis=0)
ab4 = np.mean(al4b,axis=0)
ran = 20
sframe1 =3300
sframe2 =1800
sframe3 =1300
sframe4 =1300
al1t = np.zeros((ran,11))
al2t = np.zeros((ran,11))
al3t = np.zeros((ran,11))
al4t = np.zeros((ran,11))
for i in range(ran):
    frame1 = sframe1 +i*10+1
    frame2 = sframe2 +i*10+1
    frame3 = sframe3 +i*10+1
    frame4 = sframe4 +i*10+1
    al1t[i] = alsort(np.loadtxt('hks/areamodel{:d}frame{:04d}.csv'.format(1,frame1),delimiter=','))
    al2t[i] = alsort(np.loadtxt('hks/areamodel{:d}frame{:04d}.csv'.format(2,frame2),delimiter=','))
    al3t[i] = alsort(np.loadtxt('hks/areamodel{:d}frame{:04d}.csv'.format(3,frame3),delimiter=','))
    al4t[i] = alsort(np.loadtxt('hks/areamodel{:d}frame{:04d}.csv'.format(4,frame4),delimiter=','))

In [155]:
#結果の割合

#ベースモデルを作る
base1 = np.mean(bl1[500:1100],axis=0)
base2 = np.mean(bl2[1200:1800],axis=0)
base3 = np.mean(bl3[600:1200],axis=0)
base4 = np.mean(bl4[600:1200],axis=0)
#テストモデルを作る
test1 = np.mean(np.reshape(bl1[3300:4500],(20,60,17)),axis=1)
test2 = np.mean(np.reshape(bl2[1800:3000],(20,60,17)),axis=1)
test3 = np.mean(np.reshape(bl3[1300:2500],(20,60,17)),axis=1)
test4 = np.mean(np.reshape(bl4[1300:2500],(20,60,17)),axis=1)
for name in lst:
    exec("ansbox%d =np.zeros((20,4))"%(name))
    for i,j in enumerate(lst):
#普通の結果
        exec("ansbox%d[:,i] = np.sum(np.abs(test%d-base%d),axis=1)"%(name,name,j))
    exec("indbox%d = np.argsort(ansbox%d,axis=1)+1"%(name,name))
#print(ansbox1)
#print(ansbox2)
#print(ansbox3)
#print(ansbox4)
#print(np.sum(indbox1[:,0] ==1)/20)
#print(np.sum(indbox2[:,0] ==2)/20)
#print(np.sum(indbox3[:,0] ==3)/20)
#print(np.sum(indbox4[:,0] ==4)/20)
#print(indbox1)
#print(indbox2)
#print(indbox3)
#print(indbox4)


In [157]:
#これは必要
print(np.shape(al1t-ab1))
ansbox = np.zeros((20,4))
ansbox[:,0] = np.sum(np.abs(al1t-ab1),axis=1)
ansbox[:,1] = np.sum(np.abs(al1t-ab2),axis=1)
ansbox[:,2] = np.sum(np.abs(al1t-ab3),axis=1)
ansbox[:,3] = np.sum(np.abs(al1t-ab4),axis=1)
print(np.argsort(ansbox,axis=1))
a1 = ansbox
#a1 = np.argsort(ansbox,axis=1)+1
ansbox = np.zeros((20,4))
ansbox[:,0] = np.sum(np.abs(al2t-ab1),axis=1)
ansbox[:,1] = np.sum(np.abs(al2t-ab2),axis=1)
ansbox[:,2] = np.sum(np.abs(al2t-ab3),axis=1)
ansbox[:,3] = np.sum(np.abs(al2t-ab4),axis=1)
print(np.argsort(ansbox,axis=1))
a2 = ansbox
#a2 = np.argsort(ansbox,axis=1)+1

ansbox = np.zeros((20,4))
ansbox[:,0] = np.sum(np.abs(al3t-ab1),axis=1)
ansbox[:,1] = np.sum(np.abs(al3t-ab2),axis=1)
ansbox[:,2] = np.sum(np.abs(al3t-ab3),axis=1)
ansbox[:,3] = np.sum(np.abs(al3t-ab4),axis=1)
print(np.argsort(ansbox,axis=1))
a3 = ansbox
#a3 = np.argsort(ansbox,axis=1)+1

ansbox = np.zeros((20,4))
ansbox[:,0] = np.sum(np.abs(al4t-ab1),axis=1)
ansbox[:,1] = np.sum(np.abs(al4t-ab2),axis=1)
ansbox[:,2] = np.sum(np.abs(al4t-ab3),axis=1)
ansbox[:,3] = np.sum(np.abs(al4t-ab4),axis=1)
print(np.argsort(ansbox,axis=1))
a4 = ansbox
#a4 = np.argsort(ansbox,axis=1)+1


(20, 11)
[[0 1 3 2]
 [0 1 2 3]
 [0 1 3 2]
 [0 1 3 2]
 [0 1 3 2]
 [0 1 2 3]
 [0 2 1 3]
 [0 1 3 2]
 [0 1 3 2]
 [0 1 3 2]
 [0 1 3 2]
 [0 1 3 2]
 [0 1 3 2]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 3 2]
 [0 1 3 2]
 [0 1 3 2]
 [0 1 3 2]
 [0 1 3 2]]
[[0 1 3 2]
 [1 0 3 2]
 [1 0 3 2]
 [1 0 3 2]
 [0 1 2 3]
 [0 1 2 3]
 [1 0 3 2]
 [0 1 3 2]
 [1 0 3 2]
 [1 0 3 2]
 [1 0 3 2]
 [0 1 2 3]
 [0 1 2 3]
 [1 0 3 2]
 [0 1 3 2]
 [1 0 3 2]
 [1 0 3 2]
 [1 0 2 3]
 [0 1 2 3]
 [0 1 3 2]]
[[2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]]
[[3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [1 0 3 2]
 [3 1 0 2]]


In [182]:
#mul =np.zeros((20,4)) 
#mul = np.array([1,0.75,0.5,0.25])
#合体させたもの
ma = np.max(ansbox1,axis=1)
mi = np.max(ansbox1,axis=1)
mma = np.max(a1,axis=1)
mmi = np.max(a1,axis=1)
bma = np.max(b1,axis=1)
bmi = np.max(b1,axis=1)
result = np.zeros((20,4))
for i in range(20):
#    result[i] = (ansbox1[i]-mi[i])/(ma[i]-mi[i])
#    result[i] += (a1[i]-mmi[i])/(mma[i]-mmi[i])
#    result[i] += (b1[i]-bmi[i])/(bma[i]-bmi[i])
    result[i] = (ansbox1[i]-mi[i])/(mi[i])
    result[i] += (a1[i]-mmi[i])/(mmi[i])
    result[i] += (b1[i]-bmi[i])/(bmi[i])
print(np.argsort(result,axis=1))

ma = np.max(ansbox2,axis=1)
mi = np.max(ansbox2,axis=1)
mma = np.max(a2,axis=1)
mmi = np.max(a2,axis=1)
bma = np.max(b2,axis=1)
bmi = np.max(b2,axis=1)
result = np.zeros((20,4))
for i in range(20):
    result[i] = (ansbox2[i]-mi[i])/(mi[i])
    result[i] += (a2[i]-mmi[i])/(mmi[i])
    result[i] += (b2[i]-bmi[i])/(bmi[i])
print(np.argsort(result,axis=1))


ma = np.max(ansbox3,axis=1)
mi = np.max(ansbox3,axis=1)
mma = np.max(a3,axis=1)
mmi = np.max(a3,axis=1)
bma = np.max(b3,axis=1)
bmi = np.max(b3,axis=1)
result = np.zeros((20,4))
for i in range(20):
    result[i] = (ansbox3[i]-mi[i])/(mi[i])
    result[i] += (a3[i]-mmi[i])/(mmi[i])
    result[i] += (b3[i]-bmi[i])/(bmi[i])
print(np.argsort(result,axis=1))

ma = np.max(ansbox4,axis=1)
mi = np.max(ansbox4,axis=1)
mma = np.max(a4,axis=1)
mmi = np.max(a4,axis=1)
bma = np.max(b4,axis=1)
bmi = np.max(b4,axis=1)
result = np.zeros((20,4))
for i in range(20):
    result[i] = (ansbox4[i]-mi[i])/(mi[i])
    result[i] += (a4[i]-mmi[i])/(mmi[i])
    result[i] += (b4[i]-bmi[i])/(bmi[i])
print(np.argsort(result,axis=1))


[[0 1 3 2]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 3 2]
 [1 0 3 2]
 [0 1 2 3]
 [0 2 1 3]
 [0 2 1 3]
 [1 0 3 2]
 [0 1 3 2]
 [0 1 2 3]
 [0 1 2 3]
 [0 2 1 3]
 [0 2 1 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[1 0 2 3]
 [1 0 2 3]
 [1 0 3 2]
 [1 0 3 2]
 [1 0 2 3]
 [1 0 2 3]
 [1 0 3 2]
 [1 0 2 3]
 [1 0 3 2]
 [1 0 3 2]
 [1 0 2 3]
 [1 0 2 3]
 [1 0 2 3]
 [1 3 0 2]
 [1 0 3 2]
 [1 3 0 2]
 [1 3 0 2]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]
 [2 0 1 3]]
[[3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 1 0 2]
 [3 0 1 2]
 [3 0 1 2]
 [3 1 0 2]]


In [ ]:
ここから運動情報

In [174]:
#骨格の長さを計算する関数
#def bonelen(trc):
def bonelen(trc):
    joint = trc[:,1:]
    #配列作り
    a = np.arange(17)
    a[4] = 1
    a[7] = 1
    a[10] = 1
    a[13] = 0
    a[14] = 0
    a[-2:] -=1
    c = np.zeros(17*3,dtype='int32')
    c[::3] = a*3
    c[1::3] =a*3+1
    c[2::3] =a*3+2
    jointbox = (joint[:,1*3:]-joint[:,c])**2
    jointbox = np.reshape(jointbox,(len(jointbox),17,3))
    jointlen = np.sum(jointbox,axis=2)**0.5
    return jointlen
def jointvar(trc):
    joint = trc[:,1:]
    jmean = np.mean(joint,axis=0)
    jointbox = (joint-jmean)**2
    jointbox = np.reshape(jointbox,(len(jointbox),18,3))
    jointlen = np.sum(jointbox,axis=2)**0.5
    return np.var(jointlen,axis=0)**0.5/np.mean(jointlen,axis=0)
def jointvar1(trc):
    joint = trc[:,1:]
    nosejoint = np.zeros(np.shape(joint))
    for i in range(18):
        nosejoint[:,i*3]   = joint[:,0]  
        nosejoint[:,i*3+1] = joint[:,1]
        nosejoint[:,i*3+2] = joint[:,2]
#    nosejoint[:,::3]  += joint[:,0]
#    nosejoint[:,1::3] += joint[:,1]
#    nosejoint[:,2::3] += joint[:,2]
    joint = joint-nosejoint
    jmean = np.mean(joint,axis=0)
    jointbox = (joint-jmean)**2
    jointbox = np.reshape(jointbox,(len(jointbox),18,3))
    jointlen = np.sum(jointbox,axis=2)**0.5
    jvar =  np.var(jointlen,axis=0)**0.5
    print(jvar)
#    jvar =  np.var(jointlen,axis=0)**0.5/np.mean(jointlen,axis=0)
    lst = [4,7,10,13]
#    return np.var(jointlen,axis=0)**0.5/np.mean(jointlen,axis=0)
    return jvar[lst]
    
def footlen(trc):
    joint = trc[:,1:]
    rjoint = joint[:,30:33]
    ljoint = joint[:,39:42]
    foot = np.sum((rjoint-ljoint)**2,axis=1)**0.5
    return np.max(foot)
    

In [175]:
#lst = [500,1200,600,600]
lst = [500,1200,600,600]
var1len = 4
#basevar = np.zeros((4,18))
basevar = np.zeros((4,18))
basevar1 = np.zeros((4,var1len))
basefoot = np.zeros(4)
for i in range(4):
    a = pd.read_table('trc/model{}.trc'.format(i+1),header=4)
    b = a.values
    trc = b[lst[i]:lst[i]+600,:-1]
    basevar[i] = jointvar(trc)
    basevar1[i] = jointvar1(trc)
    basefoot[i] = footlen(trc)
lst = [3300,1800,1300,1300]
#testvar = np.zeros((4,20,18))
testvar = np.zeros((4,20,18))
testvar1 = np.zeros((4,20,var1len))
testfoot = np.zeros((4,20))
for i in range(4):
    #temp = np.zeros((20,18))
    temp = np.zeros((20,18))
    temp1 = np.zeros((20,var1len))
    a = pd.read_table('trc/model{}.trc'.format(i+1),header=4)
    b = a.values
    for j in range(20):
        trc = b[lst[i]+40*j:lst[i]+300+40*j,:-1]
#        trc = b[lst[i]+60*j:lst[i]+60*(j+1),:-1]
        temp[j] = jointvar(trc)
        temp1[j] = jointvar1(trc)
        testfoot[i,j] = footlen(trc)
    testvar[i] = temp
    testvar1[i] = temp1

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:9: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  if __name__ == '__main__':


[ 0.          7.86166155 12.36816272 25.39183059 67.27526132  9.99537581
 29.75813675 73.00066902 10.33963486 45.17208575 84.47424127 11.57849269
 55.0715996  84.10936897  4.81782229  4.19633588  8.00603209  5.86497741]
[ 0.         10.47916109 12.48344915 35.66340004 71.10100569 13.26344133
 23.55232814 57.06822852 13.46417859 25.50687825 79.37879964 14.1937789
 30.70887936 92.66984742  7.82544308  7.32676911 10.10781055  9.31465984]
[ 0.          3.86415865  7.78354521 22.02249543 56.09367004  7.51326354
 22.95529741 58.89177214 11.12311861 31.94703778 77.40018283 12.43547182
 31.7609877  77.6785338   3.54868798  3.55514755  5.61642501  5.57765467]
[ 0.          8.73042742 12.26058561 26.8453424  61.60767635 10.45076636
 37.40304736 63.78247751 13.21948388 40.23045419 81.11988192 12.61938112
 40.47448369 73.42812103  6.6166341   6.47189689  8.55882921  8.54583218]


/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:24: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.


[ 0.          8.27496514 11.20931582 30.90005206 52.27921606 10.73944142
 34.66108245 83.13007173 14.924017   39.39436289 82.75726745 16.19884106
 46.2086055  88.83278262  5.49727399  5.12792885  7.45035555  6.52870418]
[ 0.          6.3758342   9.95049641 31.64786937 51.86796832 11.18458247
 31.79365296 81.26142076 11.38323007 38.07884201 79.85370059 13.31491976
 47.9359679  89.14868874  5.21864527  5.12582747  7.12736723  6.68383643]
[ 0.          7.30103631 10.19839347 29.90539284 47.13807307 11.66542835
 32.60439533 82.04595123 11.66286484 37.63883134 83.81067558 12.13363899
 46.48698681 86.96868503  6.09689311  5.35383127  8.20071526  7.1707195 ]
[ 0.          8.02412798 10.30981853 30.27880599 48.55465606 12.70735458
 30.03338994 79.74405404 12.32742802 39.78888713 83.31260753 11.48735934
 45.6606097  89.47761466  6.92692059  5.79716442  9.2851798   7.781512  ]
[ 0.          7.99961319 10.25796506 29.81442142 47.2741511  12.47824776
 29.74140399 81.16116767 12.2042739  38.8665214

In [177]:
ansbox = np.zeros((20,4))
for i in range(4):
#    ansbox[:,i] = np.mean(np.abs(testvar[0]-basevar[i]),axis=1)
    ansbox[:,i] = np.mean(np.abs(testvar1[0]-basevar1[i]),axis=1)
#    ansbox[:,i] = np.abs(testfoot[i]-basefoot[i])
    b1 = ansbox.copy()
print(np.argsort(ansbox,axis=1))
for i in range(4):
#    ansbox[:,i] = np.mean(np.abs(testvar[1]-basevar[i]),axis=1)
    ansbox[:,i] = np.mean(np.abs(testvar1[1]-basevar1[i]),axis=1)
#    ansbox[:,i] = np.abs(testfoot[i]-basefoot[i])
    b2 = ansbox.copy()
print(np.argsort(ansbox,axis=1))
for i in range(4):
#    ansbox[:,i] = np.mean(np.abs(testvar[2]-basevar[i]),axis=1)
    ansbox[:,i] = np.mean(np.abs(testvar1[2]-basevar1[i]),axis=1)
#    ansbox[:,i] = np.abs(testfoot[i]-basefoot[i])
    b3 = ansbox.copy()
print(np.argsort(ansbox,axis=1))
for i in range(4):
#    ansbox[:,i] = np.mean(np.abs(testvar[3]-basevar[i]),axis=1)
    ansbox[:,i] = np.mean(np.abs(testvar1[3]-basevar1[i]),axis=1)
#    ansbox[:,i] = np.abs(testfoot[i]-basefoot[i])
    b4 = ansbox.copy()
print(np.argsort(ansbox,axis=1))

[[0 2 3 1]
 [0 2 3 1]
 [0 2 3 1]
 [0 2 3 1]
 [0 2 3 1]
 [0 2 3 1]
 [0 2 3 1]
 [0 2 3 1]
 [0 2 3 1]
 [0 2 3 1]
 [0 2 3 1]
 [0 2 3 1]
 [0 2 3 1]
 [0 2 3 1]
 [0 2 3 1]
 [0 2 3 1]
 [0 2 3 1]
 [0 2 3 1]
 [0 2 3 1]
 [0 2 3 1]]
[[1 2 3 0]
 [1 2 3 0]
 [1 2 3 0]
 [1 2 3 0]
 [1 2 3 0]
 [1 2 3 0]
 [1 2 3 0]
 [1 2 3 0]
 [1 2 3 0]
 [1 2 3 0]
 [1 2 3 0]
 [1 2 3 0]
 [1 2 3 0]
 [1 3 2 0]
 [1 3 0 2]
 [1 3 0 2]
 [3 0 1 2]
 [3 1 0 2]
 [0 3 1 2]
 [0 3 1 2]]
[[2 3 1 0]
 [2 3 1 0]
 [2 3 1 0]
 [2 3 1 0]
 [2 3 1 0]
 [2 3 1 0]
 [2 3 0 1]
 [2 3 0 1]
 [2 3 0 1]
 [2 3 0 1]
 [2 3 0 1]
 [2 3 0 1]
 [2 3 0 1]
 [2 3 0 1]
 [2 3 0 1]
 [2 3 0 1]
 [2 3 0 1]
 [2 3 0 1]
 [2 3 1 0]
 [2 3 1 0]]
[[3 2 0 1]
 [3 2 0 1]
 [3 0 2 1]
 [3 0 2 1]
 [3 0 2 1]
 [3 0 2 1]
 [3 0 2 1]
 [3 0 2 1]
 [3 0 2 1]
 [3 0 2 1]
 [3 0 2 1]
 [3 0 2 1]
 [3 0 2 1]
 [3 0 2 1]
 [3 2 0 1]
 [3 2 0 1]
 [2 3 0 1]
 [2 0 3 1]
 [2 3 0 1]
 [2 3 0 1]]


In [95]:
a = pd.read_table('trc/model{}.trc'.format(i+1),header=4)
b = a.values


/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.
